name: deploy blog

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # 使用最新版本
        with:
          submodules: recursive    # 已包含子模块初始化

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.144.2'  # 指定版本更安全
          extended: true
      - name: Build
        run: hugo --minify -D
      
      - name: setup aliyun oss
        uses: manyuanrong/setup-ossutil@master
        with:
          #endpoint: oss-ap-southeast-1.aliyuncs.com #修改为自己的Endpoint
          #250311改为oss加速域名
          endpoint: oss-accelerate.aliyuncs.com
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

      - name: cp aliyun oss
        run: ossutil cp -rf public oss://winhugoblog/ #修改为自己的
